apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267082839:role/eksctl-eksdemo-nodegroup-eksdemo-n-NodeInstanceRole-lDzqWls5c3dG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::533267082839:user/dev
      username: dev
      groups:
        - system:masters
    - userarn: arn:aws:iam::533267082839:user/devops
      username: devops
      groups:
        - system:masters
