apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-sa
  namespace: irsa-demo
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
