apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Admin#123
        - name: MYSQL_DATABASE
          value: customerdb
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: Admin#123
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:                     
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
